project_id = "whflgkvbxlapyvrauwag"

[functions.telegram-bot]
verify_jwt = false

[functions.verify-channel]
verify_jwt = false

[functions.send-file]
verify_jwt = false

[functions.secure-api]
verify_jwt = false

[functions.upload-to-imagekit]
verify_jwt = false

[functions.monetag-postback]
verify_jwt = false
